/**
 * Theme Definitions
 * 10+ pre-built themes for the admin dashboard
 */

import { Theme } from './theme-types';

export const themes: Record<string, Theme> = {
  // Aesthetic Themes
  midnightDark: {
    id: 'midnight-dark',
    name: 'Midnight Dark',
    colors: {
      primary: '#6366f1',
      primaryForeground: '#ffffff',
      secondary: '#1e293b',
      secondaryForeground: '#e2e8f0',
      accent: '#8b5cf6',
      accentForeground: '#ffffff',
      background: '#0f172a',
      foreground: '#f1f5f9',
      card: '#1e293b',
      cardForeground: '#f1f5f9',
      popover: '#1e293b',
      popoverForeground: '#f1f5f9',
      muted: '#334155',
      mutedForeground: '#94a3b8',
      border: '#334155',
      input: '#334155',
      ring: '#6366f1',
      destructive: '#ef4444',
      destructiveForeground: '#ffffff',
      success: '#22c55e',
      successForeground: '#ffffff',
      warning: '#f59e0b',
      warningForeground: '#ffffff',
      info: '#3b82f6',
      infoForeground: '#ffffff',
    },
    fonts: {
      heading: 'Inter, system-ui, sans-serif',
      body: 'Inter, system-ui, sans-serif',
      mono: 'JetBrains Mono, monospace',
    },
    effects: {
      borderRadius: '0.5rem',
      boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.3)',
      transitions: true,
      animations: true,
    },
    preview: {
      icon: '🌙',
      description: 'Deep dark theme with indigo accents - perfect for night work',
      colorScheme: 'dark',
      category: 'aesthetic',
    },
  },

  oceanBlue: {
    id: 'ocean-blue',
    name: 'Ocean Blue',
    colors: {
      primary: '#0ea5e9',
      primaryForeground: '#ffffff',
      secondary: '#0c4a6e',
      secondaryForeground: '#e0f2fe',
      accent: '#06b6d4',
      accentForeground: '#ffffff',
      background: '#031017',
      foreground: '#ecfeff',
      card: '#0c4a6e',
      cardForeground: '#e0f2fe',
      popover: '#0c4a6e',
      popoverForeground: '#e0f2fe',
      muted: '#164e63',
      mutedForeground: '#67e8f9',
      border: '#164e63',
      input: '#164e63',
      ring: '#0ea5e9',
      destructive: '#f43f5e',
      destructiveForeground: '#ffffff',
      success: '#10b981',
      successForeground: '#ffffff',
      warning: '#f59e0b',
      warningForeground: '#ffffff',
      info: '#3b82f6',
      infoForeground: '#ffffff',
    },
    fonts: {
      heading: 'Inter, system-ui, sans-serif',
      body: 'Inter, system-ui, sans-serif',
      mono: 'JetBrains Mono, monospace',
    },
    effects: {
      borderRadius: '0.5rem',
      boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.3)',
      transitions: true,
      animations: true,
    },
    preview: {
      icon: '🌊',
      description: 'Deep ocean blues with cyan accents - calming and professional',
      colorScheme: 'dark',
      category: 'aesthetic',
    },
  },

  forestGreen: {
    id: 'forest-green',
    name: 'Forest Green',
    colors: {
      primary: '#22c55e',
      primaryForeground: '#ffffff',
      secondary: '#14532d',
      secondaryForeground: '#dcfce7',
      accent: '#16a34a',
      accentForeground: '#ffffff',
      background: '#022c22',
      foreground: '#f0fdf4',
      card: '#14532d',
      cardForeground: '#dcfce7',
      popover: '#14532d',
      popoverForeground: '#dcfce7',
      muted: '#166534',
      mutedForeground: '#86efac',
      border: '#166534',
      input: '#166534',
      ring: '#22c55e',
      destructive: '#dc2626',
      destructiveForeground: '#ffffff',
      success: '#22c55e',
      successForeground: '#ffffff',
      warning: '#d97706',
      warningForeground: '#ffffff',
      info: '#0284c7',
      infoForeground: '#ffffff',
    },
    fonts: {
      heading: 'Inter, system-ui, sans-serif',
      body: 'Inter, system-ui, sans-serif',
      mono: 'JetBrains Mono, monospace',
    },
    effects: {
      borderRadius: '0.5rem',
      boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.3)',
      transitions: true,
      animations: true,
    },
    preview: {
      icon: '🌲',
      description: 'Rich forest greens - nature-inspired for a calming workspace',
      colorScheme: 'dark',
      category: 'aesthetic',
    },
  },

  sunsetWarm: {
    id: 'sunset-warm',
    name: 'Sunset Warm',
    colors: {
      primary: '#f97316',
      primaryForeground: '#ffffff',
      secondary: '#7c2d12',
      secondaryForeground: '#ffedd5',
      accent: '#ea580c',
      accentForeground: '#ffffff',
      background: '#1a0a05',
      foreground: '#fff7ed',
      card: '#7c2d12',
      cardForeground: '#ffedd5',
      popover: '#7c2d12',
      popoverForeground: '#ffedd5',
      muted: '#9a3412',
      mutedForeground: '#fdba74',
      border: '#9a3412',
      input: '#9a3412',
      ring: '#f97316',
      destructive: '#dc2626',
      destructiveForeground: '#ffffff',
      success: '#16a34a',
      successForeground: '#ffffff',
      warning: '#f59e0b',
      warningForeground: '#ffffff',
      info: '#0ea5e9',
      infoForeground: '#ffffff',
    },
    fonts: {
      heading: 'Inter, system-ui, sans-serif',
      body: 'Inter, system-ui, sans-serif',
      mono: 'JetBrains Mono, monospace',
    },
    effects: {
      borderRadius: '0.5rem',
      boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.3)',
      transitions: true,
      animations: true,
    },
    preview: {
      icon: '🌅',
      description: 'Warm orange tones reminiscent of sunset - cozy and inviting',
      colorScheme: 'dark',
      category: 'aesthetic',
    },
  },

  // Eye-Friendly Themes
  sepiaComfort: {
    id: 'sepia-comfort',
    name: 'Sepia Comfort',
    colors: {
      primary: '#a0522d',
      primaryForeground: '#ffffff',
      secondary: '#f5f0e6',
      secondaryForeground: '#3d3329',
      accent: '#8b4513',
      accentForeground: '#ffffff',
      background: '#faf6f0',
      foreground: '#3d3329',
      card: '#f5f0e6',
      cardForeground: '#3d3329',
      popover: '#ffffff',
      popoverForeground: '#3d3329',
      muted: '#e8e0d4',
      mutedForeground: '#6b5d4d',
      border: '#d4c8b8',
      input: '#d4c8b8',
      ring: '#a0522d',
      destructive: '#c53030',
      destructiveForeground: '#ffffff',
      success: '#2f855a',
      successForeground: '#ffffff',
      warning: '#b7791f',
      warningForeground: '#ffffff',
      info: '#2b6cb0',
      infoForeground: '#ffffff',
    },
    fonts: {
      heading: 'Georgia, serif',
      body: 'Georgia, serif',
      mono: 'Courier New, monospace',
    },
    effects: {
      borderRadius: '0.5rem',
      boxShadow: '0 2px 4px -1px rgba(0, 0, 0, 0.1)',
      transitions: true,
      animations: true,
    },
    preview: {
      icon: '📖',
      description: 'Warm sepia tones - easy on the eyes for reading and writing',
      colorScheme: 'light',
      category: 'eye-friendly',
    },
  },

  softCream: {
    id: 'soft-cream',
    name: 'Soft Cream',
    colors: {
      primary: '#7c3aed',
      primaryForeground: '#ffffff',
      secondary: '#fef3c7',
      secondaryForeground: '#78350f',
      accent: '#8b5cf6',
      accentForeground: '#ffffff',
      background: '#fffbeb',
      foreground: '#451a03',
      card: '#fef3c7',
      cardForeground: '#78350f',
      popover: '#ffffff',
      popoverForeground: '#78350f',
      muted: '#fef3c7',
      mutedForeground: '#92400e',
      border: '#fcd34d',
      input: '#fcd34d',
      ring: '#7c3aed',
      destructive: '#dc2626',
      destructiveForeground: '#ffffff',
      success: '#059669',
      successForeground: '#ffffff',
      warning: '#d97706',
      warningForeground: '#ffffff',
      info: '#0284c7',
      infoForeground: '#ffffff',
    },
    fonts: {
      heading: 'Nunito, system-ui, sans-serif',
      body: 'Nunito, system-ui, sans-serif',
      mono: 'Fira Code, monospace',
    },
    effects: {
      borderRadius: '0.75rem',
      boxShadow: '0 2px 4px -1px rgba(0, 0, 0, 0.05)',
      transitions: true,
      animations: true,
    },
    preview: {
      icon: '☕',
      description: 'Gentle cream background with soft purple - reduces eye strain',
      colorScheme: 'light',
      category: 'eye-friendly',
    },
  },

  // Medical Themes
  medicalClean: {
    id: 'medical-clean',
    name: 'Medical Clean',
    colors: {
      primary: '#0891b2',
      primaryForeground: '#ffffff',
      secondary: '#ecfeff',
      secondaryForeground: '#164e63',
      accent: '#06b6d4',
      accentForeground: '#ffffff',
      background: '#f0fdfa',
      foreground: '#134e4a',
      card: '#ffffff',
      cardForeground: '#134e4a',
      popover: '#ffffff',
      popoverForeground: '#134e63',
      muted: '#ccfbf1',
      mutedForeground: '#0f766e',
      border: '#99f6e4',
      input: '#99f6e4',
      ring: '#0891b2',
      destructive: '#dc2626',
      destructiveForeground: '#ffffff',
      success: '#059669',
      successForeground: '#ffffff',
      warning: '#d97706',
      warningForeground: '#ffffff',
      info: '#2563eb',
      infoForeground: '#ffffff',
    },
    fonts: {
      heading: 'Inter, system-ui, sans-serif',
      body: 'Inter, system-ui, sans-serif',
      mono: 'Roboto Mono, monospace',
    },
    effects: {
      borderRadius: '0.375rem',
      boxShadow: '0 1px 3px -1px rgba(0, 0, 0, 0.1)',
      transitions: true,
      animations: false,
    },
    preview: {
      icon: '⚕️',
      description: 'Clinical teal and white - sterile and professional healthcare look',
      colorScheme: 'light',
      category: 'medical',
    },
  },

  medicalBlue: {
    id: 'medical-blue',
    name: 'Medical Blue',
    colors: {
      primary: '#2563eb',
      primaryForeground: '#ffffff',
      secondary: '#dbeafe',
      secondaryForeground: '#1e40af',
      accent: '#3b82f6',
      accentForeground: '#ffffff',
      background: '#eff6ff',
      foreground: '#1e3a8a',
      card: '#ffffff',
      cardForeground: '#1e3a8a',
      popover: '#ffffff',
      popoverForeground: '#1e40af',
      muted: '#dbeafe',
      mutedForeground: '#1d4ed8',
      border: '#bfdbfe',
      input: '#bfdbfe',
      ring: '#2563eb',
      destructive: '#dc2626',
      destructiveForeground: '#ffffff',
      success: '#059669',
      successForeground: '#ffffff',
      warning: '#d97706',
      warningForeground: '#ffffff',
      info: '#0284c7',
      infoForeground: '#ffffff',
    },
    fonts: {
      heading: 'Inter, system-ui, sans-serif',
      body: 'Inter, system-ui, sans-serif',
      mono: 'Roboto Mono, monospace',
    },
    effects: {
      borderRadius: '0.375rem',
      boxShadow: '0 1px 3px -1px rgba(0, 0, 0, 0.1)',
      transitions: true,
      animations: false,
    },
    preview: {
      icon: '🏥',
      description: 'Trustworthy blue tones - perfect for medical dashboards',
      colorScheme: 'light',
      category: 'medical',
    },
  },

  // Child-Friendly Themes
  playfulRainbow: {
    id: 'playful-rainbow',
    name: 'Playful Rainbow',
    colors: {
      primary: '#ec4899',
      primaryForeground: '#ffffff',
      secondary: '#fef3c7',
      secondaryForeground: '#831843',
      accent: '#f472b6',
      accentForeground: '#831843',
      background: '#fff1f2',
      foreground: '#881337',
      card: '#ffffff',
      cardForeground: '#881337',
      popover: '#ffffff',
      popoverForeground: '#831843',
      muted: '#fce7f3',
      mutedForeground: '#be185d',
      border: '#f9a8d4',
      input: '#f9a8d4',
      ring: '#ec4899',
      destructive: '#e11d48',
      destructiveForeground: '#ffffff',
      success: '#059669',
      successForeground: '#ffffff',
      warning: '#d97706',
      warningForeground: '#ffffff',
      info: '#0284c7',
      infoForeground: '#ffffff',
    },
    fonts: {
      heading: 'Comic Neue, cursive',
      body: 'Nunito, sans-serif',
      mono: 'Fira Code, monospace',
    },
    effects: {
      borderRadius: '1rem',
      boxShadow: '0 4px 8px -1px rgba(236, 72, 153, 0.2)',
      transitions: true,
      animations: true,
    },
    preview: {
      icon: '🌈',
      description: 'Fun pink and rainbow accents - delightful for young users',
      colorScheme: 'light',
      category: 'child-friendly',
    },
  },

  kidsAdventure: {
    id: 'kids-adventure',
    name: 'Kids Adventure',
    colors: {
      primary: '#22c55e',
      primaryForeground: '#ffffff',
      secondary: '#fef08a',
      secondaryForeground: '#3f6212',
      accent: '#eab308',
      accentForeground: '#3f6212',
      background: '#f7fee7',
      foreground: '#3f6212',
      card: '#ffffff',
      cardForeground: '#3f6212',
      popover: '#ffffff',
      popoverForeground: '#3f6212',
      muted: '#ecfccb',
      mutedForeground: '#65a30d',
      border: '#bef264',
      input: '#bef264',
      ring: '#22c55e',
      destructive: '#dc2626',
      destructiveForeground: '#ffffff',
      success: '#22c55e',
      successForeground: '#ffffff',
      warning: '#eab308',
      warningForeground: '#3f6212',
      info: '#0284c7',
      infoForeground: '#ffffff',
    },
    fonts: {
      heading: 'Comic Neue, cursive',
      body: 'Nunito, sans-serif',
      mono: 'Fira Code, monospace',
    },
    effects: {
      borderRadius: '1.25rem',
      boxShadow: '0 4px 12px -1px rgba(34, 197, 94, 0.2)',
      transitions: true,
      animations: true,
    },
    preview: {
      icon: '🎈',
      description: 'Adventure greens and yellows - fun and engaging for children',
      colorScheme: 'light',
      category: 'child-friendly',
    },
  },

  // Business Themes
  corporateSlate: {
    id: 'corporate-slate',
    name: 'Corporate Slate',
    colors: {
      primary: '#475569',
      primaryForeground: '#ffffff',
      secondary: '#f1f5f9',
      secondaryForeground: '#0f172a',
      accent: '#64748b',
      accentForeground: '#ffffff',
      background: '#ffffff',
      foreground: '#0f172a',
      card: '#f8fafc',
      cardForeground: '#0f172a',
      popover: '#ffffff',
      popoverForeground: '#0f172a',
      muted: '#f1f5f9',
      mutedForeground: '#64748b',
      border: '#e2e8f0',
      input: '#e2e8f0',
      ring: '#475569',
      destructive: '#dc2626',
      destructiveForeground: '#ffffff',
      success: '#059669',
      successForeground: '#ffffff',
      warning: '#d97706',
      warningForeground: '#ffffff',
      info: '#2563eb',
      infoForeground: '#ffffff',
    },
    fonts: {
      heading: 'Inter, system-ui, sans-serif',
      body: 'Inter, system-ui, sans-serif',
      mono: 'JetBrains Mono, monospace',
    },
    effects: {
      borderRadius: '0.375rem',
      boxShadow: '0 1px 3px -1px rgba(0, 0, 0, 0.1)',
      transitions: true,
      animations: false,
    },
    preview: {
      icon: '💼',
      description: 'Professional slate gray - classic corporate elegance',
      colorScheme: 'light',
      category: 'business',
    },
  },

  // Accessibility Themes
  highContrast: {
    id: 'high-contrast',
    name: 'High Contrast',
    colors: {
      primary: '#ffff00',
      primaryForeground: '#000000',
      secondary: '#000000',
      secondaryForeground: '#ffffff',
      accent: '#00ffff',
      accentForeground: '#000000',
      background: '#000000',
      foreground: '#ffffff',
      card: '#000000',
      cardForeground: '#ffffff',
      popover: '#000000',
      popoverForeground: '#ffffff',
      muted: '#1a1a1a',
      mutedForeground: '#ffffff',
      border: '#ffffff',
      input: '#ffffff',
      ring: '#ffff00',
      destructive: '#ff0000',
      destructiveForeground: '#ffffff',
      success: '#00ff00',
      successForeground: '#000000',
      warning: '#ffff00',
      warningForeground: '#000000',
      info: '#00ffff',
      infoForeground: '#000000',
    },
    fonts: {
      heading: 'Arial, sans-serif',
      body: 'Arial, sans-serif',
      mono: 'Courier New, monospace',
    },
    effects: {
      borderRadius: '0.25rem',
      boxShadow: 'none',
      transitions: false,
      animations: false,
    },
    preview: {
      icon: '🔲',
      description: 'Maximum contrast black/white - WCAG AAA compliant',
      colorScheme: 'dark',
      category: 'accessibility',
    },
  },

  // Light theme (default)
  light: {
    id: 'light',
    name: 'Light',
    colors: {
      primary: '#3b82f6',
      primaryForeground: '#ffffff',
      secondary: '#f1f5f9',
      secondaryForeground: '#0f172a',
      accent: '#6366f1',
      accentForeground: '#ffffff',
      background: '#ffffff',
      foreground: '#0f172a',
      card: '#ffffff',
      cardForeground: '#0f172a',
      popover: '#ffffff',
      popoverForeground: '#0f172a',
      muted: '#f1f5f9',
      mutedForeground: '#64748b',
      border: '#e2e8f0',
      input: '#e2e8f0',
      ring: '#3b82f6',
      destructive: '#ef4444',
      destructiveForeground: '#ffffff',
      success: '#22c55e',
      successForeground: '#ffffff',
      warning: '#f59e0b',
      warningForeground: '#ffffff',
      info: '#3b82f6',
      infoForeground: '#ffffff',
    },
    fonts: {
      heading: 'Inter, system-ui, sans-serif',
      body: 'Inter, system-ui, sans-serif',
      mono: 'JetBrains Mono, monospace',
    },
    effects: {
      borderRadius: '0.5rem',
      boxShadow: '0 1px 3px -1px rgba(0, 0, 0, 0.1)',
      transitions: true,
      animations: true,
    },
    preview: {
      icon: '☀️',
      description: 'Clean white theme - classic and versatile',
      colorScheme: 'light',
      category: 'business',
    },
  },
};

export const themeList = Object.values(themes);

export const getThemeById = (id: string): Theme | undefined => {
  return themes[id];
};

export const getThemesByCategory = (category: Theme['preview']['category']): Theme[] => {
  return themeList.filter((theme) => theme.preview.category === category);
};

export const defaultThemeId = 'midnight-dark';
